Feature/add asking feedback in fe 165
wearespindle/flindt pull request #53
Opened 2017-12-18 10:46 UTC by TomOffringa

This branch has a migration, so be sure to run that one first. Also, frontend doesn't run in docker anymore so if you want to test, hit me up.

2017-12-18 13:24 UTC, PM5544 requested changes
Apart from the NPM dep and the fact that I can only comment on frontend changes...
Awesome, ship it!

2017-12-18 13:24 UTC, PM5544 commented on frontend/package.json
> +    "react-select": "^1.1.0",
This could be removed

2017-12-20 13:25 UTC, redmerloen commented on backend/flindt/api/urls.py
> +from rest_framework.urlpatterns import format_suffix_patterns
This is not used

2017-12-20 13:25 UTC, redmerloen commented on backend/flindt/api/urls.py
> +from django.conf.urls import url
This is not used

2017-12-20 13:28 UTC, PM5544 approved these changes

2017-12-20 13:30 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            logger.info(message)
This can be removed

2017-12-20 13:30 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            if not settings.DEBUG:
This can also be removed

2017-12-20 13:30 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            logger.info(message)
Can be removed now

2017-12-20 13:30 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            if not settings.DEBUG:
Can be removed

2017-12-20 13:31 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            logger.info(message)
Can ben removed

2017-12-20 13:31 UTC, redmerloen commented on backend/flindt/feedback/models.py
> +            if not settings.DEBUG:
Can be removed

2017-12-21 10:52 UTC, merged